chore: free disk for ci (#1484)
## Rationale

CI fails due to no space...
```
Error: No space left on device : '/home/runner/runners/2.313.0/_diag/pages/e678fbe3-017c-41da-8bca-a6d70099419c_0ce2596c-30e4-5db6-a7ae-10ecfd0107a7_1.log'
```
-
https://github.com/apache/incubator-horaedb/actions/runs/7974416510/job/21770259595

## Detailed Changes
Refer https://github.com/orgs/community/discussions/25678


## Test Plan
CI